CREATE DATABASE IF NOT EXISTS slobshop;

CREATE TABLE IF NOT EXISTS `lists`
(
  `id`   INT(11) AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;